/** Styles */
import './source/styles/reset.css'
import './source/styles/globals.scss'

/** Next Imports */
import { Urbanist } from "next/font/google";

/** Components */
import Header from './source/components/header';
import { ThemeProvider } from './source/components/context';
import Footer from './source/components/footer';

const urbanist_Font = Urbanist({
    subsets: ['latin'],
    display: 'swap',
    variable: '--Urbanist_Grotesk'
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${urbanist_Font.className}`}>
                <div className="bg-animation"></div>
                <ThemeProvider >
                    <Header />
                    {children}
                    <Footer/>
                </ThemeProvider>
            </body>
        </html>
    );
}
